"""QC builder for the HLSDK studiomdl (Linux port).

Coordinate notes (verified by compiling test models, see tests/test_conventions.py):
  * `$origin 0 0 0 -90` makes studiomdl's zrotation 0, so animation root bones are stored exactly as
    written in the SMDs (engine space +X forward). We always emit it before any $sequence.
  * `$eyeposition a b c` is stored as (-b, a, c) by studiomdl, so eye(x,y,z) -> "$eyeposition y -x z".
  * `$bbox/$cbox` are raw model-space boxes. `$hbox` boxes are in bone-local space.
  * `$cliptotextures` is a no-op in this studiomdl version (it sets clip_texcoords = 0, the default):
    skins are always cropped to the used UV range - see api.uv_span_meshes for how we keep pages intact.
  * `$gamma 1.799` keeps palettes bit-exact (see text()).
"""
import os


class Sequence:
    def __init__(self, name, smds, fps=30.0, loop=False, activity=None, actweight=1,
                 motion=None, events=None, blend=None):
        self.name = name
        self.smds = list(smds)
        self.fps = fps
        self.loop = loop
        self.activity = activity
        self.actweight = actweight
        self.motion = motion        # e.g. 'LX'
        self.events = events or []  # list of (event_id, frame, options or None)
        self.blend = blend          # e.g. ('XR', -90, 90)

    def line(self):
        parts = ['$sequence "%s"' % self.name]
        parts += ['"%s"' % s for s in self.smds]
        if self.blend:
            parts.append('blend %s %g %g' % self.blend)
        parts.append('fps %g' % self.fps)
        if self.loop:
            parts.append('loop')
        if self.activity:
            parts.append('%s %d' % (self.activity, self.actweight))
        if self.motion:
            parts.append(self.motion)
        if self.events:
            ev = []
            for e in self.events:
                eid, frame = e[0], e[1]
                opt = e[2] if len(e) > 2 else None
                if opt is None:
                    ev.append('{ event %d %d }' % (eid, frame))
                else:
                    if len(opt) >= 64:
                        raise ValueError('event option too long (>=64): %r' % opt)
                    ev.append('{ event %d %d "%s" }' % (eid, frame, opt))
            parts.append(' '.join(ev))
        return ' '.join(parts)


class QC:
    def __init__(self, modelname):
        self.modelname = modelname
        self.bodies = []        # (bodypart name, [ref smd names or None for blank])
        self.eye = (0, 0, 0)
        self.bbox = None
        self.cbox = None
        self.hboxes = []        # (group, bone, mins, maxs)
        self.attachments = []   # (index, bone, pos)
        self.sequences = []
        self.rendermodes = []   # (texture, 'masked'|'additive')
        self.texgroups = []     # (name, [[tex...], [tex...]])
        self.flags = 0
        self.extra = []

    def body(self, name, smd):
        self.bodies.append((name, [smd]))

    def bodygroup(self, name, smds):
        self.bodies.append((name, list(smds)))

    def hbox(self, group, bone, mins, maxs):
        self.hboxes.append((group, bone, tuple(mins), tuple(maxs)))

    def attachment(self, index, bone, pos):
        self.attachments.append((index, bone, tuple(pos)))

    def add(self, seq):
        self.sequences.append(seq)
        return seq

    def text(self):
        L = []
        L.append('// generated by devtools/mdlkit - do not edit')
        L.append('$modelname "%s"' % self.modelname)
        L.append('$cd "."')
        L.append('$cdtexture "."')
        L.append('$scale 1.0')
        L.append('$origin 0 0 0 -90')
        L.append('$cliptotextures')
        # studiomdl gamma-corrects every palette unless gamma == 1.8, but compares float 1.8f with double 1.8
        # (always different) and truncates pow(c/255, g)*255 -> many colours lose 1. 1.799 gives g < 1 with
        # enough margin that the truncation returns exactly the source palette (verified by api).
        L.append('$gamma 1.799')
        if self.flags:
            L.append('$flags %d' % self.flags)
        ex, ey, ez = self.eye
        L.append('$eyeposition %g %g %g' % (ey, -ex, ez))
        for name, smds in self.bodies:
            if len(smds) == 1 and smds[0] is not None:
                L.append('$body "%s" "%s"' % (name, smds[0]))
            else:
                L.append('$bodygroup "%s"' % name)
                L.append('{')
                for s in smds:
                    L.append('  blank' if s is None else '  studio "%s"' % s)
                L.append('}')
        for tex, mode in self.rendermodes:
            L.append('$texrendermode "%s" %s' % (tex, mode))
        for name, groups in self.texgroups:
            L.append('$texturegroup "%s"' % name)
            L.append('{')
            for g in groups:
                L.append('  { ' + ' '.join('"%s"' % t for t in g) + ' }')
            L.append('}')
        if self.bbox:
            L.append('$bbox %g %g %g %g %g %g' % (tuple(self.bbox[0]) + tuple(self.bbox[1])))
        if self.cbox:
            L.append('$cbox %g %g %g %g %g %g' % (tuple(self.cbox[0]) + tuple(self.cbox[1])))
        for g, bone, mn, mx in self.hboxes:
            L.append('$hbox %d "%s" %.3f %.3f %.3f %.3f %.3f %.3f' % ((g, bone) + mn + mx))
        for idx, bone, p in self.attachments:
            L.append('$attachment %d "%s" %.3f %.3f %.3f' % ((idx, bone) + p))
        L += self.extra
        for s in self.sequences:
            L.append(s.line())
        return '\n'.join(L) + '\n'

    def write(self, path):
        with open(path, 'w', newline='\n') as f:
            f.write(self.text())
        return path
